tartiflette/tartiflette-asgi

tartiflette_starlette/__init__.py
tartiflette_starlette/app.py
tests/conftest.py
tests/resolvers.py
tests/test_graphql.py

Rename to TartifletteApp, clarify Starlette dependency in tests

---

CHANGELOG.md
MANIFEST.in

Add graphiql.html to MANIFEST

---

CHANGELOG.md
README.md
setup.py

Fixes #7 
Starlette 0.12.0 was released a week ago. :+1:

Upgrade to starlette>=0.12

---

CHANGELOG.md
README.md
tartiflette_starlette/app.py
tartiflette_starlette/graphql.py
tartiflette_starlette/utils.py
tests/_utils.py
tests/conftest.py
tests/test_context.py
tests/test_mount.py

Fixes #18 
Changes: see `CHANGELOG`.

Change default path

---

CHANGELOG.md
README.md
tartiflette_starlette/graphql.py
tests/resolvers.py

Rename request to req in context

---

CHANGELOG.md
README.md
tartiflette_starlette/graphql.py
tests/test_context.py
tests/test_graphql_api.py
tests/test_mount.py
tests/test_tartiflette_app.py

Omit errors field if no errors occurred

---

README.md
setup.py

Fixes #23, fixes #27.
Tip: click "View file" to view the new README.

Rewrite README

---

CHANGELOG.md
README.md
setup.py
tartiflette_starlette/app.py
tartiflette_starlette/mount.py
tests/conftest.py
tests/test_context.py
tests/test_graphiql.py
tests/test_mount.py
tests/test_tartiflette_app.py

Add support for Tartiflette 0.12

---

CHANGELOG.md
README.md
tartiflette_starlette/app.py
tartiflette_starlette/datastructures.py
tartiflette_starlette/endpoints.py
tests/resolvers.py
tests/sdl/Query.graphql
tests/test_context.py

Fixes #13
I ended up needing this for #38, so I suppose it can actually be useful for other people as well. :-)
This is an improved version of #30.

Allow extra GraphQL context

---

CHANGELOG.md
tartiflette_starlette/datastructures.py
tests/test_graphiql.py

Fix None subscription endpoint

---

README.md

Fix trailing slash on ASGI example request

---

tartiflette_starlette/endpoints.py
tests/test_mount.py

Prepend ASGI root_path to GraphQL endpoint

---

.travis.yml
requirements.txt
setup.cfg

Setup mypy

---

.travis.yml
tartiflette_starlette/app.py
tartiflette_starlette/datastructures.py
tartiflette_starlette/endpoints.py
tartiflette_starlette/middleware.py
tartiflette_starlette/mount.py
tartiflette_starlette/subscriptions/impl.py
tartiflette_starlette/subscriptions/protocol.py

Fix typing errors

---

.travis.yml

Build and install package in CI

---

requirements.txt
scripts/check
scripts/clean
scripts/lint
scripts/publish
scripts/test
setup.cfg

Add project automation scripts

---

scripts/build

Add build script

---

.travis.yml
CONTRIBUTING.md
scripts/build
scripts/publish

Use scripts in CI

---

README.md

Clarifies what this package needs at a minimum to work properly, in a dedicated section of the docs.

Add requirements section to README

---

README.md

Revamp documentation on ASGI submounting

---

.travis.yml
scripts/docs
scripts/publish
scripts/serve

Setup tooling for docs site

---

CONTRIBUTING.md
scripts/test

They went a bit out of date, esp. wr.t. helper scripts.
Also, code checks now run as part of the `test` script locally.

Update contributing guidelines

---

docs/usage.md

Fix simple typo: wnat -> want

---

scripts/check
tests/_utils.py
tests/conftest.py
tests/resolvers.py
tests/test_context.py
tests/test_graphiql.py
tests/test_graphql_api.py
tests/test_mount.py
tests/test_subscription.py
tests/test_tartiflette_app.py

The annotations were only partial, so there were a bunch of mypy errors. Better if we can have mypy lint these files and surface any types-related usage issues users might encounter.

Run type checking on `tests/`

---

requirements.txt
tests/test_context.py

Committed via https://github.com/asottile/all-repos
Unblocks #125

Use and pin Black 20

---

CHANGELOG.md
src/tartiflette_asgi/__init__.py

- Add official compatibility with Tartiflette 1.3.x. (Pull #132)

Release 0.10.0

---

CHANGELOG.md
CONTRIBUTING.md
src/tartiflette_asgi/__init__.py

- Add support for variables in query parameters. (Pull #176)

Release 0.12.0
